version: "3.8"

services:
  app:
    container_name: rtm-core-config_app2
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - .env
    environment:
      MINIO_HOST: minio
      POSTGRES_HOST: postgres
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:${PORT}
    depends_on:
      - postgres
      - minio
      - rabbitmq
  pgadmin:
    container_name: rtm-core-config_pgadmin2
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5055:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
  minio:
    container_name: rtm-core-config_minio2
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  rabbitmq:
    container_name: rtm-core-config_rabbitmq2
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  postgres:
    container_name: rtm-core-config_postgres2
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
  minio-data:
  rabbitmq-data:
  pgadmin-data: